version: '3.6'

services:
  taxajuroapi-v1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "64978:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
  calculajuroapi-v1:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "64979:80"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    